/**
 * iCloud HME 地址池 + 凭据持久化
 *
 * 两类数据都存到 electron-store（与现有账号库同等加密强度）：
 *   1. creds — iCloud cookie（HME API 用）+ 主邮箱与应用专用密码（IMAP 取码用）
 *   2. pool  — HME 地址池条目，含状态机：free → consumed/failed
 *
 * 并发分配采用单锁 mutex（一个 Promise 串行队列），保证批量并发注册时不会两个 task 抢到同一地址；
 * 注册失败的地址默认标 failed 不归还，提供"重置失败"按钮供人工救援；UI 上显示 free/consumed/failed
 * 三种状态的统计。
 */

import { app } from 'electron'
import * as path from 'path'

// 与 main/index.ts 里的账号库分两个 Store，互不干扰；KEY 不同所以加密互独立
const STORE_NAME = 'kiro-icloud-hme'
const STORE_KEY = 'kiro-icloud-hme-secret-key'

interface MinimalStore {
  get: (key: string, defaultValue?: unknown) => unknown
  set: (key: string, value: unknown) => void
  delete: (key: string) => void
}

let storePromise: Promise<MinimalStore> | null = null

async function getStore(): Promise<MinimalStore> {
  if (storePromise) return storePromise
  storePromise = (async () => {
    const StoreCtor = (await import('electron-store')).default as unknown as new (
      opts: Record<string, unknown>
    ) => MinimalStore
    const userDataDir = app.getPath('userData')
    return new StoreCtor({
      name: STORE_NAME,
      encryptionKey: STORE_KEY,
      cwd: path.join(userDataDir, 'data')
    })
  })()
  return storePromise
}

// ============ 凭据 ============

export interface IcloudCreds {
  /** 浏览器导出的 iCloud cookie 头字符串（HME API 鉴权） */
  cookie: string
  /** 主邮箱地址，用作 IMAP 用户名与"过滤掉自家地址"的依据 */
  mainEmail: string
  /** 应用专用密码（appleid.apple.com 生成，xxxx-xxxx-xxxx-xxxx 格式） */
  appPassword: string
  /** 默认 HME label / note，写在 reserve 时的元数据，便于在 iCloud 设置里识别 */
  defaultLabel?: string
  defaultNote?: string
}

const DEFAULT_LABEL = 'kiro-account-manager'
const DEFAULT_NOTE = 'Generated by Kiro Account Manager'

export async function getCreds(): Promise<IcloudCreds> {
  const store = await getStore()
  const v = (store.get('creds') as Partial<IcloudCreds> | undefined) || {}
  return {
    cookie: v.cookie || '',
    mainEmail: v.mainEmail || '',
    appPassword: v.appPassword || '',
    defaultLabel: v.defaultLabel || DEFAULT_LABEL,
    defaultNote: v.defaultNote || DEFAULT_NOTE
  }
}

export async function saveCreds(input: Partial<IcloudCreds>): Promise<IcloudCreds> {
  const store = await getStore()
  const cur = await getCreds()
  const next: IcloudCreds = {
    cookie: typeof input.cookie === 'string' ? input.cookie : cur.cookie,
    mainEmail: typeof input.mainEmail === 'string' ? input.mainEmail.trim() : cur.mainEmail,
    appPassword: typeof input.appPassword === 'string' ? input.appPassword.trim() : cur.appPassword,
    defaultLabel:
      typeof input.defaultLabel === 'string' ? input.defaultLabel.trim() : cur.defaultLabel,
    defaultNote: typeof input.defaultNote === 'string' ? input.defaultNote.trim() : cur.defaultNote
  }
  store.set('creds', next)
  return next
}

// ============ 地址池 ============

export type HmeStatus = 'free' | 'consumed' | 'failed'

export interface HmePoolEntry {
  address: string
  /** 来源：generated=应用内生成；imported=外部导入（无 anonymousId） */
  source: 'generated' | 'imported'
  status: HmeStatus
  /** Apple 侧的 anonymousId，仅 generated 来源有；用于后续 deactivate */
  anonymousId?: string
  label?: string
  /** 创建时间（ms） */
  createdAt: number
  /** 最近一次状态变更时间（ms） */
  updatedAt: number
  /** consumed/failed 时关联的 task id 或邮箱（便于追溯） */
  consumedBy?: string
  /** 失败原因，仅 failed 时有 */
  error?: string
}

export interface PoolStats {
  total: number
  free: number
  consumed: number
  failed: number
}

interface PoolDoc {
  entries: HmePoolEntry[]
}

async function loadPool(): Promise<PoolDoc> {
  const store = await getStore()
  const raw = store.get('pool', { entries: [] }) as PoolDoc
  if (!raw || !Array.isArray(raw.entries)) return { entries: [] }
  return raw
}

async function savePool(doc: PoolDoc): Promise<void> {
  const store = await getStore()
  store.set('pool', doc)
}

// ============ 单进程互斥锁（保证 checkout 串行） ============
// 不能用 Promise queue 做读改写，否则并发 checkout 时会读到同一份"快照"分配同一地址。
let lockChain: Promise<unknown> = Promise.resolve()

function withLock<T>(fn: () => Promise<T>): Promise<T> {
  const next = lockChain.then(fn, fn)
  // 不让前一次失败传染到下一次（把 chain 钳到 ignore-error）
  lockChain = next.catch(() => undefined)
  return next
}

// ============ 池子 CRUD ============

export async function getPool(): Promise<HmePoolEntry[]> {
  const { entries } = await loadPool()
  return entries.slice() // 拷贝防止外部突变
}

export async function getPoolStats(): Promise<PoolStats> {
  const entries = await getPool()
  let free = 0,
    consumed = 0,
    failed = 0
  for (const e of entries) {
    if (e.status === 'free') free++
    else if (e.status === 'consumed') consumed++
    else if (e.status === 'failed') failed++
  }
  return { total: entries.length, free, consumed, failed }
}

/**
 * 把若干新地址塞入池子，按 address 去重保留旧条目（避免 import/generate 重复入池）。
 * 返回实际新增数量。
 */
export async function addEntries(entries: HmePoolEntry[]): Promise<number> {
  return withLock(async () => {
    const cur = await loadPool()
    const known = new Set(cur.entries.map((e) => e.address.toLowerCase()))
    let added = 0
    for (const e of entries) {
      const key = (e.address || '').trim().toLowerCase()
      if (!key) continue
      if (known.has(key)) continue
      cur.entries.push({ ...e, address: key, createdAt: Date.now(), updatedAt: Date.now() })
      known.add(key)
      added++
    }
    await savePool(cur)
    return added
  })
}

/**
 * 批量原子分配：从 free 池里取 count 个，立刻标 consumed 并返回。
 * 不足时只返回当前能给的，调用方负责检查。
 */
export async function checkoutBatch(count: number, consumedBy?: string): Promise<string[]> {
  if (count <= 0) return []
  return withLock(async () => {
    const cur = await loadPool()
    const out: string[] = []
    for (const e of cur.entries) {
      if (out.length >= count) break
      if (e.status !== 'free') continue
      e.status = 'consumed'
      e.consumedBy = consumedBy
      e.updatedAt = Date.now()
      out.push(e.address)
    }
    await savePool(cur)
    return out
  })
}

/** 单个分配（手动模式或试运行用，不并发场景下用） */
export async function checkoutOne(consumedBy?: string): Promise<string | null> {
  const arr = await checkoutBatch(1, consumedBy)
  return arr[0] || null
}

/**
 * 把已分配出去但实际没用上的地址归还到 free（仅当当前是 consumed 才允许，避免覆盖 failed）。
 * 用途：批量任务被取消、抢到地址但本轮没启动的退还。
 */
export async function releaseAddresses(addresses: string[]): Promise<number> {
  if (addresses.length === 0) return 0
  return withLock(async () => {
    const cur = await loadPool()
    const set = new Set(addresses.map((a) => a.toLowerCase()))
    let n = 0
    for (const e of cur.entries) {
      if (!set.has(e.address)) continue
      if (e.status !== 'consumed') continue
      e.status = 'free'
      e.consumedBy = undefined
      e.updatedAt = Date.now()
      n++
    }
    await savePool(cur)
    return n
  })
}

/** 注册失败时把地址置为 failed（带原因） */
export async function markFailed(address: string, error: string): Promise<boolean> {
  return withLock(async () => {
    const cur = await loadPool()
    for (const e of cur.entries) {
      if (e.address !== address.toLowerCase()) continue
      e.status = 'failed'
      e.error = error
      e.updatedAt = Date.now()
      await savePool(cur)
      return true
    }
    return false
  })
}

/** 把 failed 全部重置回 free（人工救援按钮使用） */
export async function resetFailedToFree(): Promise<number> {
  return withLock(async () => {
    const cur = await loadPool()
    let n = 0
    for (const e of cur.entries) {
      if (e.status !== 'failed') continue
      e.status = 'free'
      e.error = undefined
      e.updatedAt = Date.now()
      n++
    }
    await savePool(cur)
    return n
  })
}

/** 删除指定地址（不调用 Apple 侧的 deactivate，仅本地清理） */
export async function removeEntries(addresses: string[]): Promise<number> {
  if (addresses.length === 0) return 0
  return withLock(async () => {
    const cur = await loadPool()
    const set = new Set(addresses.map((a) => a.toLowerCase()))
    const before = cur.entries.length
    cur.entries = cur.entries.filter((e) => !set.has(e.address))
    await savePool(cur)
    return before - cur.entries.length
  })
}

/** 整池清空 */
export async function clearPool(): Promise<void> {
  await withLock(async () => {
    await savePool({ entries: [] })
  })
}

/** 通过 anonymousId 反查地址（用于 deactivate 后从池里移除） */
export async function findByAnonymousId(anonymousId: string): Promise<HmePoolEntry | null> {
  const entries = await getPool()
  for (const e of entries) {
    if (e.anonymousId === anonymousId) return e
  }
  return null
}
